trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool: pravin-agent

stages:
  - stage:
    displayName: Terraform Infra Pipeline
    jobs:
      - job:
        displayName: Terraform init plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'pravin-connection'
              backendAzureRmResourceGroupName: "RG-DEV"
              backendAzureRmStorageAccountName: 'vikrantstorage9987'
              backendAzureRmContainerName: 'pravinnekramvikram'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'pravin-connection'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'pravin-connection'