trigger:
  branches:
    include:
      - main

pool:
  name: Infrapipeline

stages:
  - stage: Terraform
    displayName: "Terraform Infra Pipeline"

    jobs:
      - job: TerraformJob
        displayName: "Terraform Init Plan Apply"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "pravin-connection"
              backendAzureRmResourceGroupName: "RG-DEV"
              backendAzureRmStorageAccountName: "vikrantstorage9987"
              backendAzureRmContainerName: "pravinnekramvikram"
              backendAzureRmKey: "terraform.tfstate"

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: "azurerm"
              command: "plan"
              environmentServiceNameAzureRM: "pravin-connection"

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              environmentServiceNameAzureRM: "pravin-connection"

          - task: TerraformTask@5
            displayName: "Terraform Output"
            inputs:
              provider: "azurerm"
              command: "output"
              environmentServiceNameAzureRM: "pravin-connection"